# Pre-commit Hooks Konfiguration
repos:
  # Standard Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Leerzeichen am Zeilenende
      - id: end-of-file-fixer # Zeilenende am Dateiende
      - id: check-yaml # YAML-Syntax
      - id: check-added-large-files # Dateigröße max 800KB
      - id: check-merge-conflict # Merge-Konflikte
      - id: mixed-line-ending # Unix-Zeilenenden (LF)

  # Python Code-Formatierung
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13

  # Import-Sortierung
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Code-Style & Dokumentation
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings # Docstring-Check
        args: [--max-line-length=100]
