repos:
  # Standard Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Entfernt Leerzeichen am Zeilenende
      - id: end-of-file-fixer # Stellt sicher, dass Dateien mit einer neuen Zeile enden
      - id: check-yaml # Validiert die YAML-Syntax
      - id: check-added-large-files # Verhindert große Dateien (> 800 KB)
        args: ['--maxkb=800'] # Erhöht das Limit auf 800 KB
      - id: check-merge-conflict # Warnt vor verbleibenden Merge-Konflikten
      - id: mixed-line-ending # Konvertiert zu Unix-Zeilenenden (LF)

  # Python Code-Formatierung
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13
        files: \.py$ # Nur Python-Dateien prüfen

  # Import-Sortierung
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: \.py$ # Nur Python-Dateien prüfen

  # Code-Style & Dokumentation
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings # Docstring-Check
        args: [--max-line-length=100, --ignore=D203]
        files: \.py$ # Nur Python-Dateien prüfen

  # Typprüfung
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - types-Pillow
        files: \.py$

  # LaTeX Syntaxprüfung (optional)
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.24.4
    hooks:
      - id: latexindent
        args: ['-l']
        files: '.*\.tex$'

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
